version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "latest"
  commands:
     - npm ci
     # The site was created by running `vitepress init`
     # and following the official guide
     # https://vitepress.dev/guide/getting-started
     - ./node_modules/.bin/vitepress build docs
     - mkdir -p $READTHEDOCS_OUTPUT/
     - mv docs/.vitepress/dist $READTHEDOCS_OUTPUT/html
